### ISSUE TITLE
How to add drinks and liquors?

### ISSUE THREAD

**Issue by PanderMusubi** [amasciul/Drinks#56]
How can drinks and liquors get added to the API?

**Comment by amasciul** [comment]
Hi, the data for the app is contained on a server which backend is only accessible to me. You're free to suggest any drink or liquor that you think should be added.

**Comment by PanderMusubi** [comment]
Thanks, will send you via email.

**Comment by PanderMusubi** [comment]
The new version is looking very nice! Thanks. 

Did you manage to make any progress on the API cocktails I suggested per email to be added?
